version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cloudsync-postgres
    environment:
      POSTGRES_USER: cloudsync
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudsync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: cloudsync-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    restart: unless-stopped

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
        /usr/bin/mc mb myminio/cloudsync;
        /usr/bin/mc policy set public myminio/cloudsync;
        exit 0;
      "

  # Uncomment to enable API development container
  # api:
  #   build:
  #     context: .
  #     dockerfile: ./cloudsync/api/Dockerfile.dev
  #   container_name: cloudsync-api
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - minio
  #   volumes:
  #     - ./:/app
  #   environment:
  #     DB_HOST: postgres
  #     DB_USER: cloudsync
  #     DB_PASSWORD: password
  #     DB_NAME: cloudsync
  #     S3_ENDPOINT: http://minio:9000
  #     S3_ACCESS_KEY: minioadmin
  #     S3_SECRET_KEY: minioadmin
  #     S3_BUCKET: cloudsync

volumes:
  postgres_data:
  minio_data: 